arch:
  - 'osl42-x86_64'
# arch_warn_on_failure:
arch_ignore_failure:
  - 'sled11-x86-gcc4.x'
- 'sled11-x86_64-gcc4.x'

doc:
  - echo "No documentation to build"

doc_dir: ''

test:
  - python setup.py test
